# Generated by Django 4.2.20 on 2025-04-08 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=100, null=True)),
                ('marketplace_app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('query_url', models.URLField()),
                ('payments_url', models.URLField()),
                ('live_mode', models.BooleanField(blank=True, null=True)),
                ('test_mode', models.BooleanField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Integration',
                'verbose_name_plural': 'Payment Integrations',
            },
        ),
    ]
