# Generated by Django 4.2.20 on 2025-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintegration',
            name='live_apikey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintegration',
            name='live_publishablekey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintegration',
            name='test_apikey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintegration',
            name='test_publishablekey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
