# Generated by Django 4.2.20 on 2025-04-08 18:02

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentintegration_live_apikey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintegration',
            name='image_url',
            field=models.URLField(help_text='Enter a secure HTTPS image URL.', validators=[payment.models.validate_https_url]),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='payments_url',
            field=models.URLField(help_text='Enter the payments endpoint URL (must start with https://).', validators=[payment.models.validate_https_url]),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='query_url',
            field=models.URLField(help_text='Enter the query endpoint URL (must start with https://).', validators=[payment.models.validate_https_url]),
        ),
    ]
