# Generated by Django 4.2.20 on 2025-04-30 13:38

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentintegration_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=False)),
                ('request_payload', models.JSONField()),
                ('api_key', models.CharField(max_length=255)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('merchant_id', models.CharField(max_length=255)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='description',
            field=models.TextField(blank=True, default='Chingup Payment Gateway', null=True),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='image_url',
            field=models.URLField(default='https://storage.googleapis.com/msgsndr/h9yc7BtsLVSheMdIWErB/media/67f6e510d496fe1be9a98d20.jpeg'),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='live_publishablekey',
            field=models.CharField(blank=True, help_text='For ChingUp You can add Merchant Id.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='name',
            field=models.CharField(default='ChingUp', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='payments_url',
            field=models.URLField(default='https://chingup.vyntec.co/payment', help_text='Enter the payments endpoint URL (must start with https://).', validators=[payment.models.validate_https_url]),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='query_url',
            field=models.URLField(default='https://chingup.vyntec.co/verify-payment/', help_text='Enter the query endpoint URL (must start with https://).', validators=[payment.models.validate_https_url]),
        ),
        migrations.AlterField(
            model_name='paymentintegration',
            name='test_publishablekey',
            field=models.CharField(blank=True, help_text='For ChingUp You can add Merchant Id.', max_length=255, null=True),
        ),
    ]
